#!/usr/bin/env bash
# If miniconda is not installed download the installer and run it
if [[ ! -d $HOME/miniconda3 ]]; then
    bash <(curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh)
fi
