#!/usr/bin/env bash
# If miniconda is not installed download the installer and run it
if [[ ! -d $HOME/miniconda3 ]]; then
  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  bash ~/miniconda.sh -b
  rm ~/miniconda.sh
fi
